import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css'
import Button from './components/Button';

export const metadata = {
  title: 'Exemplo - 23',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>

        <nav className='d-flex gap-2 p-3 justify-content-center'>
          <Button endereco="https://www.google.com.br" texto="Google" />
          <Button endereco="https://www.cnn.com.br" texto="CNN" />
          <Button endereco="https://www.nyt.com" texto="NYT" />
        </nav>

        {children}

        
      </body>
    </html>
  )
}
