import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css'
import Button from './components/Button';

export const metadata = {
  title: 'Exemplo - 22',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>

        <nav className='d-flex gap-2 p-3 justify-content-center'>
          <Button />
          <Button />
          <Button />
        </nav>

        {children}

        
      </body>
    </html>
  )
}
